version: "3.8"

services:
    web:
        build:
            context: ./build/runtime/${PHP_VERSION}
        container_name: ${HTTP_CONTAINER_NAME}
        ports:
            - ${HTTP_LOCAL_PORT}:${HTTP_CONTAINER_PORT}
        volumes:
            - ./vhosts:/etc/apache2/sites-enabled
            - ${PROJECT}:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - APP_NAME=${APP_NAME}
            - APP_DEBUG=${APP_DEBUG}
            - APP_CACHE=${APP_CACHE}
            - DB_HOST=${DATABASE_CONTAINER_IP}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_NAME=${DB_NAME}
        networks:
            rowles:
                ipv4_address: ${HTTP_CONTAINER_IP}

    database:
        image: mysql:8
        container_name: ${DATABASE_CONTAINER_NAME}
        ports:
            - ${DATABASE_LOCAL_PORT}:${DATABASE_CONTAINER_PORT}
        volumes:
            - ${MYSQL_EPHEMERAL_STORAGE}:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_USER=${DB_USER}
            - MYSQL_DATABASE=${DB_NAME}
        networks:
            rowles:
                ipv4_address: ${DATABASE_CONTAINER_IP}

networks:
    rowles:
        external: true
        name: ${NETWORK_NAME}